const constants = {
  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_ERROR: "SIGNUP_ERROR",

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",

  ADD_NOTE_REQUEST: "ADD_NOTE_REQUEST",
  ADD_NOTE_SUCCESS: "ADD_NOTE_SUCCESS",
  ADD_NOTE_ERROR: "ADD_NOTE_ERROR",
  ADD_NOTE_RESET: "ADD_NOTE_RESET",

  UPDATE_NOTE_REQUEST: "UPDATE_NOTE_REQUEST",
  UPDATE_NOTE_SUCCESS: "UPDATE_NOTE_SUCCESS",
  UPDATE_NOTE_ERROR: "UPDATE_NOTE_ERROR",
  UPDATE_NOTE_RESET: "UPDATE_NOTE_RESET",

  GET_NOTES_REQUEST: "GET_NOTES_REQUEST",
  GET_NOTES_SUCCESS: "GET_NOTES_SUCCESS",
  GET_NOTES_ERROR: "GET_NOTES_ERROR",

  DELETE_NOTE_REQUEST: "DELETE_NOTE_REQUEST",
  DELETE_NOTE_SUCCESS: "DELETE_NOTE_SUCCESS",
  DELETE_NOTE_ERROR: "DELETE_NOTE_ERROR",
  DELETE_NOTE_RESET: "DELETE_NOTE_RESET",

  ADD_TRANCHE_REQUEST: "ADD_TRANCHE_REQUEST",
  ADD_TRANCHE_SUCCESS: "ADD_TRANCHE_SUCCESS",
  ADD_TRANCHE_ERROR: "ADD_TRANCHE_ERROR",
  ADD_TRANCHE_RESET: "ADD_TRANCHE_RESET",

  CREATE_TEMPLATE_REQUEST: "CREATE_TEMPLATE_REQUEST",
  CREATE_TEMPLATE_SUCCESS: "CREATE_TEMPLATE_SUCCESS",
  CREATE_TEMPLATE_ERROR: "CREATE_TEMPLATE_ERROR",

  LIST_TEMPLATE_REQUEST: "LIST_TEMPLATE_REQUEST",
  LIST_TEMPLATE_SUCCESS: "LIST_TEMPLATE_SUCCESS",
  LIST_TEMPLATE_ERROR: "LIST_TEMPLATE_ERROR",

  UPDATE_TEMPLATE_REQUEST: "UPDATE_TEMPLATE_REQUEST",
  UPDATE_TEMPLATE_SUCCESS: "UPDATE_TEMPLATE_SUCCESS",
  UPDATE_TEMPLATE_ERROR: "UPDATE_TEMPLATE_ERROR"
};

export default constants;
